### ISSUE TITLE
Page listant les notifications

### ISSUE THREAD

**Issue by ChantyTaguan** [ChantyTaguan/zds-site#12]
Avec 
- filtres sur le type de notifications
- tri selon la date (ascendant/descendant)
- ??

**Comment by Situphen** [comment]
Est-ce qu'on fait une page pour toutes les notifications ou une page de notification par module (tutoriels, articles, forums, etc) ? Dans tous les cas, je pense que le filtrage et le tri est obligatoire !

**Comment by ChantyTaguan** [comment]
A priori, je ferais une page unique, avec éventuellement plusieurs possibilités de tri. Mais faut voir. Si les différents types de notifs sont visuellement identifiables, ça peut suffire je pense.

**Comment by GerardPaligot** [comment]
@ChantyTaguan tu peux soit nous donner les droits, soit m'assigner à cette tâche ?

**Comment by GerardPaligot** [comment]
@Situphen Il existe quelque chose de visuel côté front pour combiner des filtres et des tris ?

**Comment by Situphen** [comment]
https://zestedesavoir.com/membres/articles/?type=validate

Donc il suffit de trouver le gabarit correspondant et c'est bon ! ;)

**Comment by GerardPaligot** [comment]
C'est exactement ce qu'il me fallait, merci !

**Comment by GerardPaligot** [comment]
@Situphen Encore une question : si je veux la liste des icônes avec leurs codes associés, je vais où ?

**Comment by Situphen** [comment]
Je ne suis pas sur à 100% mais tu vas dans https://github.com/zestedesavoir/zds-site/tree/dev/assets/images/sprite puis tu choisis ton icône.

Si tu veux `cross.png`, ce sera `<div class="ico-after cross"></div>`. Si tu veux `cross-blue.png`, ce sera `<div class="ico-after cross blue"></div>`. :)

**Comment by GerardPaligot** [comment]
Merci !
