### ISSUE TITLE
Utiliser des sous-classes pour les abonnements plutôt qu'un attribut type

### ISSUE THREAD

**Issue by ChantyTaguan** [ChantyTaguan/zds-site#15]
Histoire de rendre tout ça plus propre :)

J'ai fait un truc qui m'a l'air sympa et qui fonctionne, sur ma branche zep_24_notif_new_modele. Je vous laisse jeter un oeil avant de merger.

**Comment by ChantyTaguan** [comment]
Bon, j'ai carrément fait une PR, je me dis que ce sera plus simple pour vous de voir les changements comme ça.

Par contre, github me dit que je ne peux pas merger directement parce que j'ai des conflits, alors que j'ai fais un rebase :(

**Comment by Situphen** [comment]
@ChantyTaguan : tu as fais `git fetch origin` avant de faire `git rebase origin/zep_24_notif` ?

**Comment by ChantyTaguan** [comment]
J'utilise pas la ligne de commande (bouuuuu), mais a priori oui. Enfin j'ai fait un pull de la branche zep_24_notif avant de rebaser zep_24_notif_new_model dessus.

**Comment by Situphen** [comment]
Bizarre, bizarre...

**Comment by GerardPaligot** [comment]
Je ne sais pas ce que tu as fais mais tu n'as sans doute pas _rebase_ par rapport à la bonne branche en tout cas. Les modifications que tu as fais dans le fichier `notification/views.py` ne contiennent pas mes modifications.

**Comment by GerardPaligot** [comment]
J'ai fais le rebase de ta branche que j'ai [pushé sur mon dépôt](https://github.com/GerardPaligot/zds-site/tree/zep_24_notif_new_model). Tu peux cloturer ton ancienne PR, copier la branche de mon dépôt sur ton dépôt local, la pusher sur ton repo et faire une nouvelle PR. :)

Sinon, je n'ai pas encore regardé le code mais mes tests sur la liste des notifications passent toujours donc rien que pour ça, bien joué !

**Comment by ChantyTaguan** [comment]
Ah, j'avais pas vu ton dernier message ! Nickel merci, je fais ça ce midi ou ce soir.

Mais je comprend vraiment pas ce qu'il s'est passé... D'autant que sur mon ordi, j'ai bien toutes tes modifications, que ce soit sur `notification.views.py` ou sur les autres fichiers...

**Comment by GerardPaligot** [comment]
Est-ce que tu as fais un `git push -f` pour forcer la mise à jour de la branche distante ?

**Comment by GerardPaligot** [comment]
Je ferais mes retours quand il y aura la nouvelle PR

**Comment by ChantyTaguan** [comment]
C'te chantage !

J'ai clické sur le bouton push de SourceTree :( Je suppose que ça donne un `git push`, pas un `git push -f`...

**Comment by GerardPaligot** [comment]
C'est ce que je me suis dis quand tu as dis que tu utilisais un GUI plutôt que la ligne de commande. J'ai des collègues qui utilise aussi SourceTree et ce logiciel ne permet pas le push force, ce qui est aberrant puisqu'il permet le rebase mais bon.

**Comment by ChantyTaguan** [comment]
Voilà voilà #17 :)
