### ISSUE TITLE
Se mettre à jour par rapport au dépôt officiel

### ISSUE THREAD

**Issue by GerardPaligot** [ChantyTaguan/zds-site#18]
Récemment, j'ai développé le refactoring du module des forums et il a été mergé dans la branche dev. Malheureusement pour nous, ce merge implique des conflits pas cool pour cette ZEP. Il faudrait donc se mettre à jour par rapport au dépôt officiel un coup.

Il y a 2 solutions :
1. Soit @ChantyTaguan tu t'en charges parce que ton dépôt accueil la ZEP.
2. Soit je m'en charge mais je ne pourrais pas faire de PR. Il faudra que je rebase, que je push mon rebase dans une branche avec le même nom que la branche que nous utilisons pour la ZEP puis de faire la brute et de faire un push force pour remplacer la branche ici.

Dans les 2 cas, il faudra faire un push force avec les risques de régressions qui vont avec. Personnellement, je peux m'en charger si tu veux Taguan. C'est vraiment comme tu veux mais du coup, faut geler le développement d'ici là.

**Comment by GerardPaligot** [comment]
Ce rebase est horrible à faire !

**Comment by GerardPaligot** [comment]
Piouf, j'ai passé **toute** ma soirée dessus mais la branche est rebase [ici](https://github.com/GerardPaligot/zds-site/tree/zep_24_notif), les tests des notifications et des forums passent et il n'y a plus d'erreurs flakes.

@ChantyTaguan si ça te va, on peut faire un push force de cette branche sur la branche de ton dépôt. :) Regarde quand même rapidement le code pour être sûr que tout y est. C'était un rebase laborieux !

**Comment by ChantyTaguan** [comment]
Top ça ! Merci pour le boulot ! Je regarde demain sans faute !

**Comment by GerardPaligot** [comment]
Bon d'après Travis, les tests du côté des articles ne passent pas (effectivement, chose que je n'avais pas vérifié). Je regarde ça demain. Là, il est trop tard. :)

**Comment by GerardPaligot** [comment]
@ChantyTaguan Dit moi, est-ce que les signaux du côté des articles ont fonctionné un jour ?

**Comment by ChantyTaguan** [comment]
Au moins partiellement, mais j'avoue qu'à force de revenir en arrière et refactorer, c'est bien possible que ce soit un peu le bordel dans les modules autre que le forum.

**Comment by ChantyTaguan** [comment]
C'est surtout pour ça qu'il faudrait que je repasse sur chaque issue, histoire de retester ce qui est en place et voir exactement ce qu'il reste à faire. Parc que là, j'ai fait un petit peu de tout un peu partout, principalement pour vérifier que le modèle tenait la route dans un maximum de cas. Mais du coup, c'était pas très organisé... Et le refactoring à rallonge n'a rien arrangé, au contraire.

De ce que j'ai vu de ta branche, ça m'a l'air tout à fait OK. Dès que t'es prêt on peut pusher ça (violemment) sur ma branche. J'aurai normalement une soirée complète demain pour remettre bien tout à plat.

**Comment by GerardPaligot** [comment]
> Mais du coup, c'était pas très organisé... Et le refactoring à rallonge n'a rien arrangé, au contraire.

Les commits ont parlé d'eux-même pendant le rebase. Je ne comptais plus le nombre de fois ou j'ai retiré ce que je venais de rajouter et inversement mais c'est normal. C'est quelque chose qui était nouveau dans le projet et c'était pas possible de tomber juste dès le premier coup.

> De ce que j'ai vu de ta branche, ça m'a l'air tout à fait OK. Dès que t'es prêt on peut pusher ça (violemment) sur ma branche. J'aurai normalement une soirée complète demain pour remettre bien tout à plat.

J'aurais bien aimé mais il me reste encore 1 test à faire passer au vert mais impossible d'y arriver. C'est `test_post_unread` dans les tests des notifications. En local il fonctionne mais impossible de le faire fonctionner sur Travis. Si tu as une idée, je suis preneur ...

**Comment by ChantyTaguan** [comment]
C'est bizarre, on dirait qu'il marque le post3 unread au lieu du post1... Mais je vois pas pourquoi, et surtout je vois pas pourquoi ce serait différent sur Travis...

**Comment by GerardPaligot** [comment]
J'ai simplifié le test hier soir avant d'aller me coucher et [travis est content](https://travis-ci.org/GerardPaligot/zds-site/builds/64329182). Par conte, je pourrais pas pushé avant ce soir.

**Comment by GerardPaligot** [comment]
Google I/O oblige, je n'ai pas eu le temps de continuer cette issue. Par contre, nous sommes bon ? Est-ce que nous pouvons remplacer ma branche par celle actuelle sur ton dépôt ?

**Comment by ChantyTaguan** [comment]
J'ai pas encore récupéré ta branche parce que je ne sais pas trop comment procéder avec git.

Je fais un checkout de ta branche sous un autre nom, je merge violemment avec ma branche en gardant tous tes changements puis je push (toujours violemment) ?

**Comment by GerardPaligot** [comment]
Comme tu m'as mis contributeur, je pense que je peux le faire aussi mais ça pourrait être un bon exercice pour toi.

En fait, c'est plutôt simple :
1. Tu dois récupérer ma branche.
2. Ma branche a déjà le même nom que la branche qu'on veut remplacer chez toi donc aucun souci là dessus.
3. Puis tu fais un push force de la branche sur ton dépôt pour écraser ta branche par la mienne.

**Comment by ChantyTaguan** [comment]
Ok, j'y arrivais pas parce que ma branche ne traquait pas la tienne.

A priori, c'est fait. J'espère que j'ai pas fait de bêtises ^__^

**Comment by GerardPaligot** [comment]
Comment ça se fait qu'il y a un commit de merge avec des choses dedans ? (comment ça se fait qu'il y a un commit de merge tout court en fait ?)

**Comment by ChantyTaguan** [comment]
heu... Quand j'ai fait le checkout de ta branche ça l'a mergé avec la mienne. Vu que tu as fait un rebase ça me paraissait logique jusqu'à maintenant. Maintenant j'ai peur :(

**Comment by GerardPaligot** [comment]
Voilà, je l'ai supprimé. Le rebase, c'est justement pour éviter les merge en fait. Donc faire un rebase, puis un merge, c'est pas très pertinent.

Pour information, comme l'histoire de la branche a été modifié, il faudra que tu retires la branche par un `git checkout`, le `git pull` ne fonctionnera pas (en fait oui mais le `git pull` fait un `merge` en fait. On se retrouve avec le problème initial).
